### ISSUE TITLE
sbt compile nao compila

### ISSUE THREAD

**Issue by ppKrauss** [lexml/lexml-parser-projeto-lei#10]
Usando UBUNTU 18 LTS, instalação Java padrão (`sudo  apt install openjdk-8-jdk`)  e instalação Scala   conforme [scala-lang.org](https://www.scala-lang.org/download/), ambas fresquinhas...

Ao compilar com `sbt compile` na raiz do projeto surgiram as seguintes mensagens e erros:

```
[info] Updated file /home/sandbox/lexml-parser-projeto-lei/project/build.properties: set sbt.version to 1.2.8
[info] Loading project definition from /home/sandbox/lexml-parser-projeto-lei/project
[info] Updating ProjectRef(uri("file:/home/sandbox/lexml-parser-projeto-lei/project/"), "lexml-parser-projeto-lei-build")...
[info] downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.11.1/log4j-core-2.11.1-tests.jar ...
[info] 	[SUCCESSFUL ] org.apache.logging.log4j#log4j-core;2.11.1!log4j-core.jar(test-jar) (4327ms)
[info] Done updating.
[info] Set current project to lexml-parser-projeto-lei (in build file:/home/sandbox/lexml-parser-projeto-lei/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Updating ...
[info] Done updating.
[info] Compiling 24 Scala sources to /home/sandbox/lexml-parser-projeto-lei/target/scala-2.12/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.7. Compiling...
[info]   Compilation completed in 12.001s.
[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/ProjetoLei.scala:50:5: To compile XML syntax, the scala.xml package must be on the classpath.
[error] Please see https://github.com/scala/scala-xml for details.
[error]     <projetolei>
[error]     ^
[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/block/Block.scala:68:33: To compile XML syntax, the scala.xml package must be on the classpath.
[error] Please see https://github.com/scala/scala-xml for details.
[error]   lazy val toNodeSeq: NodeSeq = <Block/>
[error]                                 ^
[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/docx/DOCXReader.scala:26:13: To compile XML syntax, the scala.xml package must be on the classpath.
[error] Please see https://github.com/scala/scala-xml for details.
[error]         Seq(<span style={styleStr}>{nodes}</span>)
[error]             ^
[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/metadado/Metadado.scala:152:3: To compile XML syntax, the scala.xml package must be on the classpath.
[error] Please see https://github.com/scala/scala-xml for details.
[error] 		<Proposicao>
[error] 		^
[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/output/LexmlRenderer.scala:186:11: To compile XML syntax, the scala.xml package must be on the classpath.
[error] Please see https://github.com/scala/scala-xml for details.
[error]           <Dispositivo id={ d.id } textoOmitido={
[error]           ^
[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/output/html/HtmlRenderer.scala:68:37: To compile XML syntax, the scala.xml package must be on the classpath.
[error] Please see https://github.com/scala/scala-xml for details.
[error] 		case RotuloArtigo(1,None,true) => <span class="rotuloDispositivo">Artigo </span> <span class="numeroDispositivo">único.</span>
[error] 		                                  ^
[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/rotulo/RotuloDispositivo.scala:8:33: To compile XML syntax, the scala.xml package must be on the classpath.
[error] Please see https://github.com/scala/scala-xml for details.
[error]   lazy val toNodeSeq: NodeSeq = <Rotulo nivel={ nivel.toString }/>
[error]                                 ^
[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/xhtml/XHTML.scala:282:7: To compile XML syntax, the scala.xml package must be on the classpath.
[error] Please see https://github.com/scala/scala-xml for details.
[error]       <html><body><div>{ pars.map(p ⇒ <p>{ p }</p>) }</div></body></html>
[error]       ^
[error] 8 errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 16 s, completed 09/05/2019 14:00:10
```

**Comment by joaoli13** [comment]
A compilação deste projeto deve ser feita com o maven.

Att

Joao Lima
De: Peter [mailto:notifications@github.com]
Enviada em: quinta-feira, 9 de maio de 2019 14:07
Para: lexml/lexml-parser-projeto-lei <lexml-parser-projeto-lei@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [lexml/lexml-parser-projeto-lei] sbt compile nao compila (#10)


Usando UBUNTU 18 LTS, instaleções Java e Scala fresquinhas e conforme scala-lang.org<https://www.scala-lang.org/download/>...

Ao compilar com sbt compile na raiz do projeto surgiram as seguintes mensagens e erros:

[info] Updated file /home/sandbox/lexml-parser-projeto-lei/project/build.properties: set sbt.version to 1.2.8



[info] Loading project definition from /home/sandbox/lexml-parser-projeto-lei/project



[info] Updating ProjectRef(uri("file:/home/sandbox/lexml-parser-projeto-lei/project/"), "lexml-parser-projeto-lei-build")...



[info] downloading https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.11.1/log4j-core-2.11.1-tests.jar ...



[info]  [SUCCESSFUL ] org.apache.logging.log4j#log4j-core;2.11.1!log4j-core.jar(test-jar) (4327ms)



[info] Done updating.



[info] Set current project to lexml-parser-projeto-lei (in build file:/home/sandbox/lexml-parser-projeto-lei/)



[info] Executing in batch mode. For better performance use sbt's shell



[info] Updating ...



[info] Done updating.



[info] Compiling 24 Scala sources to /home/sandbox/lexml-parser-projeto-lei/target/scala-2.12/classes ...



[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.7. Compiling...



[info]   Compilation completed in 12.001s.



[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/ProjetoLei.scala:50:5: To compile XML syntax, the scala.xml package must be on the classpath.



[error] Please see https://github.com/scala/scala-xml for details.



[error]     <projetolei>



[error]     ^



[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/block/Block.scala:68:33: To compile XML syntax, the scala.xml package must be on the classpath.



[error] Please see https://github.com/scala/scala-xml for details.



[error]   lazy val toNodeSeq: NodeSeq = <Block/>



[error]                                 ^



[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/docx/DOCXReader.scala:26:13: To compile XML syntax, the scala.xml package must be on the classpath.



[error] Please see https://github.com/scala/scala-xml for details.



[error]         Seq(<span style={styleStr}>{nodes}</span>)



[error]             ^



[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/metadado/Metadado.scala:152:3: To compile XML syntax, the scala.xml package must be on the classpath.



[error] Please see https://github.com/scala/scala-xml for details.



[error]                <Proposicao>



[error]                ^



[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/output/LexmlRenderer.scala:186:11: To compile XML syntax, the scala.xml package must be on the classpath.



[error] Please see https://github.com/scala/scala-xml for details.



[error]           <Dispositivo id={ d.id } textoOmitido={



[error]           ^



[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/output/html/HtmlRenderer.scala:68:37: To compile XML syntax, the scala.xml package must be on the classpath.



[error] Please see https://github.com/scala/scala-xml for details.



[error]                case RotuloArtigo(1,None,true) => <span class="rotuloDispositivo">Artigo </span> <span class="numeroDispositivo">único.</span>



[error]                                                  ^



[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/rotulo/RotuloDispositivo.scala:8:33: To compile XML syntax, the scala.xml package must be on the classpath.



[error] Please see https://github.com/scala/scala-xml for details.



[error]   lazy val toNodeSeq: NodeSeq = <Rotulo nivel={ nivel.toString }/>



[error]                                 ^



[error] /home/sandbox/lexml-parser-projeto-lei/src/main/scala/br/gov/lexml/parser/pl/xhtml/XHTML.scala:282:7: To compile XML syntax, the scala.xml package must be on the classpath.



[error] Please see https://github.com/scala/scala-xml for details.



[error]       <html><body><div>{ pars.map(p ⇒ <p>{ p }</p>) }</div></body></html>



[error]       ^



[error] 8 errors found



[error] (Compile / compileIncremental) Compilation failed



[error] Total time: 16 s, completed 09/05/2019 14:00:10

**Comment by ppKrauss** [comment]
> A compilação deste projeto deve ser feita com o maven. Att Joao Lima De: Peter 

Olá, obrigado!

Ok, falta registrar no README do projeto que o comando mais simples é 

    cd lexml-parser-projeto-lei
    mvn install -nsu

Explicando: o comando *install* ao invés de outro (não referenciar pacote) e a opção *nsu* (no-snapshot-updates) para garantir que  compile localmente o repositorio baixado do git. O teste básico também rodou,

    mvn test

Resta agora saber **como roda (?)** o projeto, e se tem algum exemplo real e ver os resultados.
