### ISSUE TITLE
Erro de artigos numéricos seguidos imediatamente pela letra O

### ISSUE THREAD

**Issue by laurocesar** [lexml/lexml-parser-projeto-lei#11]
O parser do artigo 12 abaixo retorna o texto sem a primeira pela "O", assim:

texto: s Termos de Ajuste serão submetidos previamente à Consultoria Jurídica junto ao Ministério da Saúde para emissão de parecer. Brasília, 26 de dezembro de 2011; 190o da Independência e 123o da República.  DILMA ROUSSEFF  Miriam Belchior

Ao que parece, o parser precisa considerar que quando há um espaço, a letra "O" maiúscula seguida de número não é um indicador de ordinal.

```
LEI Nº 12.567, DE 26 DE DEZEMBRO DE 2011.
Abre ao Orçamento Fiscal da União, em favor dos Ministérios da Justiça e da Defesa, crédito especial no valor global de R$ 199.843.160,00, para os fins que especifica, e dá outras providências.
A PRESIDENTA DA REPÚBLICA Faço saber que o Congresso Nacional decreta e eu sanciono a seguinte Lei: 
Art. 12 Os Termos de Ajuste serão submetidos previamente à Consultoria Jurídica junto ao Ministério da Saúde para emissão de parecer.
Brasília, 26 de dezembro de 2011; 190o da Independência e 123o da República. 
DILMA ROUSSEFF
 Miriam Belchior
```

**Comment by joaoraf** [comment]
Resolvido em 072f42ea.
